In [1]:
import numpy as np

In [2]:
A = np.array([[11,12,13,14], [15,16,17,18]])
print(A)

[[11 12 13 14]
 [15 16 17 18]]


In [5]:
# least squares y ~= ax+b = Ax (bias b를 합침)
# x는 하나의 feature (입력값) / y는 target(출력값)
# 𝐴tAX = Atb  (여기서 b는 y를 가리킴)  


x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])

In [6]:
# concatnate a constant term

A = np.vstack([x, np.ones(len(x))]).T
A 

array([[0., 1.],
       [1., 1.],
       [2., 1.],
       [3., 1.]])

In [7]:
# create a matrix A * A

At_A = A.T.dot(A)
At_A

array([[14.,  6.],
       [ 6.,  4.]])

In [8]:
At_y = A.T.dot(y)
At_y

array([8.3, 2.2])

In [9]:
# solve for x

from numpy.linalg import solve
c = solve(At_A, At_y)
c

array([ 1.  , -0.95])