In [1]:
import numpy as np

In [2]:
A = np.array([[11,12,13,14], [15,16,17,18]])
print(A)

[[11 12 13 14]
 [15 16 17 18]]


In [3]:
# least squares y ~= ax+b
# input data
x = np.array([0, 1, 2, 4])
y = np.array([-1, 0.2, 0.9, 2.1])

In [4]:
# concatnate a constant term
A = np.vstack([x, np.ones(len(x))]).T
A 

array([[0., 1.],
       [1., 1.],
       [2., 1.],
       [4., 1.]])