In [1]:
import numpy as np

In [4]:
c = np.array([1,2,3])
print(c.shape)
print(c)
print(c[1])

(3,)
[1 2 3]
2


In [6]:
r = np.array([[1,2,3]])
print(r.shape)
print(r)
print(r[0,1])

(1, 3)
[[1 2 3]]
2


In [8]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [11]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [12]:
d = np.random.random((2,2))
print(d)

[[0.60237277 0.90913004]
 [0.99746971 0.75638187]]


In [13]:
A = np.array([[1,2], [3,4], [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
B = np.array([[11,12,13,14],[15,16,17,18]])
print(B)

[[11 12 13 14]
 [15 16 17 18]]


In [16]:
np.dot(A, B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [18]:
A = np.array([[60,5.5,1],[65,5,0],[55,6,1]])
b = np.array([66,70,78])

In [19]:
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
from numpy.linalg import inv

In [21]:
A_inv = inv(A)
print(A_inv)

[[ 0.08695652  0.00869565 -0.08695652]
 [-1.13043478  0.08695652  1.13043478]
 [ 2.         -1.         -1.        ]]


In [22]:
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
x = A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [24]:
from numpy.linalg import solve

In [25]:
x = solve(A, b)
x

array([ -0.43478261,  19.65217391, -16.        ])