# Numpy

* Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy 

In [1]:
import numpy as np

## Arrays

* A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
* We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
# Create a rank 1 array
a = np.array([1,2,3])

print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
# Create a rank 2 array   (rank A = dim Col A)
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)

print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


* Numpy also provides many functions to create arrays

In [4]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [5]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [6]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [7]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
e = np.random.random((2,2))
print(e)

[[0.82412037 0.74671637]
 [0.15986842 0.19928077]]


## Array indexing

* Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [9]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


* A slice of an array is a view into the same data, so modifying it will modify the original array

In [11]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])

2
77


* You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing.

In [12]:
a = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])

# Two ways of accessing the data in the middle row of the array
# Mixing integer indexing with slices yields an array of lower rank
# while using only slices yields an array of the same rank as the 
# original array:

row_r1 = a[1, :]   # Rank 1 view of the second row of a
row_r2 = a[1:2, :] # Rank 2 view of the second row of a 
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# We can make the same distinction when accessing columns of an array:

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


* Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarrary of the original array. In contrast, integer array indexing allows you to construct arbirarary arrays using the data from another array.

In [13]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

# An example of integer array indexing
# The returned array will have shape(3,) 
# a[0,0], a[1,1], a[2,0]
print(a[[0,1,2],[0,1,0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0,0], a[1,1], a[2,0]]))

# When using integer array indexing, you can reuse the same 
# element from the source array:
print(a[[0,0],[1,1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


* One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix

In [14]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


* Boolean array indexing: Boolean array indexing lets you pick out artitrary elements of an array/ Frequently this type ofindexing is used to select the elements of an array that satisfy some condition.

In [15]:
a = np.array([[1,2],[3,4],[5,6]])

# Find the elements of a that are bigger than 2
bool_idx = (a > 2)
print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values fo bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

* Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [16]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.int64)
print(x.dtype)

int32
float64
int64


## Array math

In [17]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [18]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [19]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [20]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [21]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


* Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the 'dot' function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 'dot' is available both as a function in the numpy module and as an instance method of array objects:

In [22]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [23]:
# inner product of vectors; both procude 219

print(v.dot(w))
print(np.dot(v, w))

219
219


In [24]:
# Matrix / vector product; both produce the rank 1 array [29 67]

print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [25]:
# Matrix / Matrix product; both produce the rank 2 array

print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


* Numpy provides many useful functions for performing computations on arrays; one of the most useful is 'sum'

In [26]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))
print(np.sum(x, axis=0)) # Compute sum of each column
print(np.sum(x, axis=1)) # Compute sum of each row

10
[4 6]
[3 7]


* Transpose

In [28]:
x = np.array([[1,2],[3,4]])

print(x)
print(x.T)


# Note that taking the tranpose of a rank 1 array does nothing
v = np.array([1,2,3])

print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

## Numpy Documentation

In [29]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)    # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


* This works; however when the matrix x is very large, computing and explict loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v viertically, then performing elementwise summation of x and vv. 

In [7]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

# Stack 4 copies of v on top of each other
vv = np.tile(v,(4,0))
print(vv)

# Add x and vv elementwise
y = x + vv
print(y)

[]


In [5]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
