# Numpy

* Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy 

In [3]:
import numpy as np

## Arrays

* A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
* We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [4]:
# Create a rank 1 array
a = np.array([1,2,3])

print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [9]:
# Create a rank 2 array   (rank A = dim Col A)
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)

print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


* Numpy also provides many functions to create arrays

In [10]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [14]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [15]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
e = np.random.random((2,2))
print(e)

[[0.74421254 0.15670745]
 [0.29801165 0.8517177 ]]


## Array indexing

* Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

## Datatypes

## Array math

## Broadcasting

## Numpy Documentation